[project]
name = "smibhid"
version = "0.1.0"
description = "SMIBHID firmware and host tools."
requires-python = ">=3.9"

dependencies = [
    "fastapi>=0.111.0",
    "pydantic>=2.0",
    "pytest>=8.4.2",
]

[project.scripts]
smibhid-openapi = "tools.smibhid-openapi.app:main"
